name: fastapi-app
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - fastapi>=0.111.0
      - uvicorn[standard]>=0.30.0
      - SQLAlchemy>=2.0.25
      - pydantic>=2.7.0
      - pydantic-settings>=2.2.1
      - python-jose[cryptography]>=3.3.0
      - passlib[bcrypt]>=1.7.4
      - pytest>=8.0.0
      - httpx>=0.27.0
      - pre-commit>=3.7.0




